services:
    Asdoria\SyliusQuickShoppingPlugin\Factory\BulkAddToCartCommandFactory:
        arguments:
            $cartContext: '@sylius.context.cart'
            $orderItemFactory: '@sylius.factory.order_item'
            $addToCartCommandFactory: '@sylius.factory.add_to_cart_command'
            $orderItemQuantityModifier: '@sylius.order_item_quantity_modifier'
